# Autogenerated wrapper script for igraph_jll for x86_64-linux-gnu
export libigraph

JLLWrappers.@generate_wrapper_header("igraph")
JLLWrappers.@declare_library_product(libigraph, "libigraph.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libigraph,
        "lib/libigraph.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
